### PR TITLE
Rename screenshots branch Issue#22 fix

### LINKED ISSUE #22: Rename Screenshots to assets
In our repo we have a `Screenshots` directory, we want to rename it to `assets`

This change also needs updating the URL of the image in the README file.

**Steps to work on**
- Add a comment here if you are working on it.
- Create PR.
- Work on a feature branch, do not work on the master branch
- No duplicate PRs
- First Contributor to comment here gets to work on this

### PR DESCRIPTION
**Pull request by AMosa3d**
Closes #22
Renamed folder completed along with README.md file.

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
> Renamed folder completed along with README.md file.

you need to tag the issue number here also. Something like this `Closes #22`

**Comment by arshadkazmi42** [comment]
@AMosa3d Looks good. Thank you for working on this.

**Comment by arshadkazmi42** [comment]
@AMosa3d Congrats on your first PR

**Comment by AMosa3d** [comment]
@arshadkazmi42 Thanks, I appreciate that :D

**Pull request merged**
